server:
  port: 8081
#  address: 0.0.0.0

spring:
  application:
    name: mysociety

  #    sql:
  #      init:
  #        mode: always
  #        schema-locations: classpath:DBSCRIPT/schema.sql
  #        data-locations:
  #          - classpath:DBSCRIPT/v1_states.sql
  #          - classpath:DBSCRIPT/v2_cities.sql

  web:
    resources:
      static-locations: file:uploads/
  datasource:
    url: jdbc:postgresql://localhost:5432/societydb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: shivaniraskar0408@gmail.com
    password: qhml xhqn meom bwsc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
